default:
  image: rust:1.77.2-alpine3.18

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

.rust_container_template: &rust_container_stable
  image: rust:1.77.2-buster
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $CARGO_HOME

.rust_container_template: &rust_container_night
  image: rustlang/rust:nightly-buster
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $CARGO_HOME

stages:
  - build
  - lint
  - test
  - docs

check:
  <<: *rust_container_stable
  stage: build
  script:
    - cargo check --release

build:
  <<: *rust_container_stable
  stage: build
  needs:
  - check
  script:
  - cargo build --verbose --release && mv target/release/gourd gourd && mv target/release/gourd-wrapper gourd-wrapper
  artifacts:
    when: on_success
    name: binaries (musl-x86_64)
    expose_as: binaries
    paths:
      - gourd
      - gourd-wrapper

fmt:
  <<: *rust_container_night
  stage: lint
  needs:
    - build
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check
  allow_failure: true

clippy:
  <<: *rust_container_stable
  stage: lint
  needs:
    - build
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --release --all-targets -- -D warnings
  allow_failure: true


coverage:
  <<: *rust_container_night
  stage: test
  needs:
    - build
  before_script:
    - cargo install cargo-tarpaulin
  script:
    - cargo tarpaulin --out Xml --root . --manifest-path Cargo.toml
  coverage: '/\d+.\d+\% coverage,.*lines covered/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
  allow_failure: true

tests:
  <<: *rust_container_night
  stage: test
  needs:
    - build
  before_script:
    - cargo install cargo2junit
  script:
    - cargo test -- -Z unstable-options --format json --report-time | $CARGO_HOME/bin/cargo2junit > results.xml
  artifacts:
    when: always
    paths:
      - results.xml
    reports:
      junit: results.xml

maintainer_docs:
  image: registry.gitlab.com/islandoftex/images/texlive:latest
  stage: docs
  allow_failure: true
  needs: []
  script: cd docs/maintainer && ./compile.sh
  artifacts:
    when: on_success
    name: maintainer documentation
    expose_as: maintainer documentation
    paths:
    - gourd-maintainer-documentation.pdf

rustdoc:
  <<: *rust_container_stable
  stage: docs
  needs: [build]
  script: cargo rustdoc
  allow_failure: true
  artifacts:
    when: on_success
    access: all
    name: rustdoc
    expose_as: rustdoc
    paths:
      - target/doc/

user_docs:
  image: alpine
  stage: docs
  needs: []
  script:
    - apk add groff
    - cd docs/user/
    - pwd
    - ls -la
    - ./compile-html.sh
  allow_failure: true
  artifacts:
    when: on_success
    access: all
    name: user documentation (man)
    expose_as: user documentation
    paths:
      - docs/user/gourd-manpage.html
      - docs/user/gourd.conf-manpage.html
