[package]
name = "gourd"
version = "0.1.5-alpha"
edition = "2021"
default-run = "gourd"
authors = [
  "Mikołaj Gazeel <m.j.gazeel@student.tudelft.nl>",
  "Lukáš Chládek <l@chla.cz>",
  "Ανδρέας Τσατσάνης <a.tsatsanis@student.tudelft.nl>",
  "Jan Piotrowski <j.p.piotrowski@student.tudelft.nl>",
  "Rūta Giedrytė <r.giedryte@student.tudelft.nl>"
]

[dependencies]
elf = "0.7.4"

tokio = { version = "1", features = ["full"] }
futures = "0.3.30"

libc = "0.2"

serde = { version = "1.0", features = ["derive"] }
toml = "0.8.12"

reqwest = { version = "0.12.4", features = ["blocking", "json"] }

clap = { version = "4.5.4", features = ["derive", "cargo"] }
anstyle = "1.0.7"

chrono = { version = "0.4", features = ["serde"]}

anyhow = "1"

thiserror = "1"

tempdir = "0.3.7"

[dev-dependencies]
easybench = "1.1.1"

[[bin]]
name = "gourd"
path = "src/main.rs"

[[bin]]
name = "gourd_wrapper"
path = "src/wrapper_binary.rs"

# This target can be enabled to check the doctests
# See here: https://github.com/rust-lang/rust/issues/50784
# [lib]
# name = "doctest"
# path = "src/main.rs"
