[package]
name = "gourd"
version = "0.1.0-alpha"
edition = "2021"

authors = [
  "Mikołaj Gazeel <m.j.gazeel@student.tudelft.nl>",
  "Lukáš Chládek <l.chladek@student.tudelft.nl>",
  "Andreas Tsatsanis <a.tsatsanis@student.tudelft.nl>",
  "Jan Piotrowski <j.p.piotrowski@student.tudelft.nl>",
  "Rūta Giedrytė <r.giedryte@student.tudelft.nl>"
]

[dependencies]

[dev-dependencies]
easybench = "1.1.1"
