[package]
name = "gourd"
version = "0.1.0-alpha"
edition = "2021"
default-run = "gourd"
authors = [
  "Mikołaj Gazeel <m.j.gazeel@student.tudelft.nl>",
  "Lukáš Chládek <l@chla.cz>",
  "Andreas Tsatsanis <a.tsatsanis@student.tudelft.nl>",
  "Jan Piotrowski <j.p.piotrowski@student.tudelft.nl>",
  "Rūta Giedrytė <r.giedryte@student.tudelft.nl>"
]

[dependencies]
elf = "0.7.4"

tokio = { version = "1", features = ["full"] }
futures = "0.3.30"

libc = "0.2"

serde = { version = "1.0", features = ["derive"] }
toml = "0.8.12"

reqwest = { version = "0.12.4", features = ["blocking", "json"] }

clap = { version = "4.5.4", features = ["derive"] }
anstyle = "1.0.7"

[dev-dependencies]
easybench = "1.1.1"
tempdir = "0.3.7"

[[bin]]
name = "gourd"
path = "src/main.rs"

[[bin]]
name = "gourd-wrapper"
path = "src/wrapper_binary.rs"
