[package]
name = "gourd"
version = "0.1.0-alpha"
edition = "2021"

authors = [
  "Mikołaj Gazeel <m.j.gazeel@student.tudelft.nl>",
  "Lukáš Chládek <l@chla.cz>",
  "Andreas Tsatsanis <a.tsatsanis@student.tudelft.nl>",
  "Jan Piotrowski <j.p.piotrowski@student.tudelft.nl>",
  "Rūta Giedrytė <r.giedryte@student.tudelft.nl>"
]

[dependencies]
elf = "0.7.4"
libc = "0.2"

serde = { version = "1.0", features = ["derive"] }

toml = "0.8.12"

[dev-dependencies]
easybench = "1.1.1"
tempdir = "0.3.7"

[[bin]]
name = "gourd-wrapper"
path = "src/wrapper_binary.rs"
