# Example `gourd.toml` for the Gourd Experiment Scheduler
#
# "Grid search"
# A simple experiment that tries all combinations of parameters
# for an input.

# Put all outputs and metrics in the same folder
output_path = "experiments"
metrics_path = "experiments"
experiments_folder = "experiments"

# This is our first program, named '3dspace'.
# The binary takes three numbers which are the dimensions of a 3d lattice,
# then it outputs all the vectors in that lattice.
[program.3dspace]
binary = "./3dspace"


# This input is parameterized, see below.
[input.grid]
arguments = ["subparam|side_length.x", "param|depth", "subparam|side_length.y"]

# Specified below are the parameters for the '3dspace' program.

# These parameters specify the possible depths of the lattice.
[parameter.depth]
values = ["5", "10", "20"]

# These sub parameters control the plane size of the lattice.
# These are conjoined, i.e. 10 will only be ever used with 30, etc.
[parameter.side_length.sub.x]
values = ["10", "15", "20"]

[parameter.side_length.sub.y]
values = ["30", "45", "30"]
