
output_path = ""
metrics_path = ""
experiments_folder = ""
wrapper = ""

[program.test.git]
git_uri = "./repo/"
commit_id = "07566620bd74d3f57dd9d0ef5a9cc8681b210659"
build_command = "cp test.sh run.sh"
path = "run.sh"

[input.input_ten]
arguments = ["10"]
