
output_path = ""
metrics_path = ""
experiments_folder = ""
wrapper = ""

[program.fast_fib]
binary = "fast_fib"
next = ["fast_fast_fib"]

[program.fast_fast_fib]
binary = "fast_fast_fib"

[program.slow_fib]
binary = "slow_fib"

[program.hello]
binary = "hello"

[input.input_twelve]
file = "./src/integration/inputs/12.in"
arguments = ["12"]

[input.hello]
file = "./src/integration/inputs/hello.in"
arguments = ["hello"]

[label.correct]
regex = "144"
priority = 1
