
output_path = ""
metrics_path = ""
experiments_folder = ""
wrapper = ""

[program.fibonacci]
binary = "slow_fib"
afterscript = "./src/integration/programs/2.sh"

[input.input_twelve]
file = "./src/integration/inputs/12.in"
arguments = ["12"]

[label.output_was_one]
regex = ".*1.*"
priority = 4

[label.output_was_not_one]
regex = ".+"
priority = 3
